baseURL = "https://gokarna-hugo.netlify.app"
defaultContentLanguage = "de"
languageCode = "de"
enableEmoji = true
enableRobotsTXT = true
theme = "gokarna"
title = "DontCallThisWebsite"

# Define the copyright notice for your site. The notice will only be displayed on page Kinds.
# The years of 'date' and 'lastmod' in the front matter are used to create a date range for your copyrighted material.
#copyright = "Verbatim copying and distribution of this entire article are permitted worldwide, without royalty, in any medium, provided this notice is preserved."

# Hugo lets you choose the color scheme for the codeblocks.
# You can choose from the options here: https://xyproto.github.io/splash/docs/all.html
# You can choose one of this preselection: monokai, emacs, trac, perldoc, nord and nordic.
pygmentsStyle = "nord"

[params]
  # Inject arbitrary HTML via the <head> tag
  # Best used for importing custom JavaScript, CSS, or analytics
  # customHeadHTML = ""
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  # Choose the color shown when hyperlinks are hovered over
  # Default is #FF4D4D
  accentColor = "#185C7C"
  
  # Set the content font-size.
  # Default is 17.5px
  #fontSize = "17.5px"

  # Resource URL for the site avatar (home page and header)
  avatarURL = "/images/avatar.webp"

  # Describe the avatar for screen readers
  avatarAltText = "avatar"

  # Set the avatar's size: size-xs, size-s, size-m, size-l & size-xl
  avatarSize = "size-l"

  # Configure how post dates are displayed
  #dateFormat = "January 2, 2006"
  
  # Configure how post dates are displayed
  # with date format Tokens
  # See https://gohugo.io/functions/time/format/
  # Friday, January 27, 2023
  #dateFormat = ":date_full"
  # January 27, 2023
  dateFormat = ":date_long"
  # Jan 27, 2023
  #dateFormat = ":date_medium"
  # 1/27/23
  #dateFormat = ":date_short"
  # 11:44:58 pm Pacific Standard Time
  #dateFormat = ":time_full"
  # 11:44:58 pm PST
  #dateFormat = ":time_long"
  # 11:44:58 pm
  #dateFormat = ":time_medium"
  # 11:44 pm
  #dateFormat = ":time_short"
  
  # Home page meta description
  description = "Huhn – Ei – Küken – Gockel! Gute Unterhaltung vom mittleren Niveau."
  
  # Second line of the Home page meta description
  description2 = "»Wo geströmt wird, wird auch programmiert«"

  # Footer text (i.e. author/project name)
  footer = "Der Gockel"

  # Define SEO keywords
  metaKeywords = ["stream", "twitch", "geschmeidig", "käse", "chatbot"]

  # Define how many posts are displayed on the home page
  # showPostsOnHomePage must be "popular" or "recent"
  numberPostsOnHomePage = 4

  # Display a "back to top" button on posts and pages: true, false
  # May not render on smaller screen sizes
  showBackToTopButton = true

  # Display a post’s estimated reading time in minutes.
  displayReadingTime = false

  # Display posts on the home page:
  # "popular" (order posts by weight)
  # "recent" (order posts by date)
  # "", unset (do not display)
  showPostsOnHomePage = ""

  # Show the previous and next post in your timeline: "true", "false"
  # Incompatible with Weight
  togglePreviousAndNextButtons = false

  # Display icons on the homepage. The specified name should exactly match one of the names from the icons directory.
  # If you want to add more icons, you can download the svg directly from https://simpleicons.org and
  # place them in your local icons directory (/static/svg/icons/)
  socialIcons = [
    {name = "github", url = "https://github.com/dontcallmechicken"},
    {name = "twitch", url = "https://www.twitch.tv/dontcallmechicken"},
    {name = "youtube", url = "https://www.youtube.com/channel/UCA1mifjFo7ImSZeXYBL1j6g"},
    {name = "suno", url = "https://suno.com/@dcmc"},
    #{name = "discord", url = "https://example.com"},
    #{name = "steam", url = "https://example.com"},
    #{name = "email", url = "mailto:example@example.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

#  [[menu.main]]
#    name = "Projects"
#    pre = "<span data-feather='code'></span>"
#    url = "/projects/"
#    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Strøm"
    pre = "<span data-feather='play'></span>"
    url = "/stream/"
    weight = 5

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/dontcallmechicken/dontcallmechicken.github.io"
    weight = 6

  #[[menu.main]]
    #identifier = "buymeacoffee"
    #pre = "<span data-feather='coffee'></span>"
    #url = "https://www.buymeacoffee.com/avijitgupta"
    #weight = 7

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 8

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = false

